import { expect, test } from './helpers/e2e-test';
import { e2eState, openEmptyApp } from './helpers/app';
import { makeReferenceImage } from './helpers/fixtures';

for (const theme of ['dark', 'light'] as const) {
  test(`empty image editor stays compact and adds actual references in ${theme}`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width: 1600, height: 1100 });
    await page.addInitScript(mode => {
      localStorage.setItem('novus.theme.mode', mode);
      window.__NOVUS_MANUAL_ACCEPTANCE__ = true;
    }, theme);
    await openEmptyApp(page);
    await page.evaluate(() => window.__NOVUS_E2E__!.createModule('image_generation', { x: 430, y: 90 }));
    const card = page.locator('[data-module-type="image_generation"]');
    await card.getByRole('button', { name: 'Open image generation editor' }).click();
    const preview = card.locator('.module-node__generation-editor-preview');
    const tray = card.getByLabel('Image generation reference slots', { exact: true });
    const prompt = card.locator('.module-node__prompt-workspace');
    const controls = card.locator('.module-node__generation-control-bar');
    await expect(tray).toContainText('0 / 20');
    await expect(tray.locator('.connected-agent-media-slots__index')).toHaveCount(0);
    await expect(tray.locator('.connected-agent-media-slots__item')).toHaveCount(0);
    const add = tray.getByRole('button', { name: '添加参考图片 / Add reference image' });
    await expect(add).toBeVisible();
    await expect(add.locator('svg')).toHaveCount(1);
    const layout = async () => {
      const nodeBox = (await card.boundingBox())!;
      const previewBox = (await preview.boundingBox())!;
      const trayBox = (await tray.boundingBox())!;
      const promptBox = (await prompt.boundingBox())!;
      const controlsBox = (await controls.boundingBox())!;
      const zoom = await page.locator('.react-flow__viewport').evaluate(element => new DOMMatrixReadOnly(getComputedStyle(element).transform).a);
      expect(previewBox.height / zoom).toBeGreaterThanOrEqual(220);
      expect(previewBox.height / zoom).toBeLessThanOrEqual(260);
      expect(trayBox.y - (previewBox.y + previewBox.height)).toBeCloseTo(0, 0);
      expect(promptBox.y - (trayBox.y + trayBox.height)).toBeCloseTo(0, 0);
      expect(controlsBox.y - (promptBox.y + promptBox.height)).toBeCloseTo(0, 0);
      expect(controlsBox.y + controlsBox.height).toBeLessThanOrEqual(nodeBox.y + nodeBox.height + 1);
      expect(controlsBox.y + controlsBox.height).toBeLessThan(1100);
      await expect(preview.locator('.module-node__generation-empty-stage')).toHaveCSS('border-top-width', '0px');
      await expect(preview.locator('.module-node__generation-empty-stage')).toHaveCSS('box-shadow', 'none');
    };
    await layout();
    await card.getByRole('combobox', { name: 'Image generation model route' }).selectOption('comfly-gpt-image-2');
    await expect(card.getByRole('region', { name: 'GPT 参数' })).toBeVisible();
    await layout();
    await card.getByRole('textbox', { name: 'Image generation prompt' }).fill('Keep the complete product shape');
    await expect(card.getByRole('button', { name: 'Image generation quality' })).toBeVisible();
    await expect(card.getByRole('button', { name: 'Image generation format' })).toBeVisible();
    await expect(card.getByRole('button', { name: 'Image generation background' })).toBeVisible();
    await page.screenshot({ path: testInfo.outputPath(`image-empty-compact-${theme}.png`) });
    const fixture = makeReferenceImage('实际参考.png', [68, 130, 94, 255], { width: 900, height: 1600 });
    const picker = page.waitForEvent('filechooser');
    await add.click();
    await (await picker).setFiles({ name: fixture.name, mimeType: fixture.mimeType, buffer: fixture.buffer });
    await expect.poll(async () => (await e2eState(page)).edgeCount).toBe(1);
    await expect(tray).toContainText('1 / 20');
    await expect(tray.locator('img')).toHaveCount(1);
    await expect(tray.locator('.connected-agent-media-slots__index')).toHaveCount(1);
    const reference = tray.locator('img');
    const expectUniformReference = async () => {
      await expect(tray).toHaveAttribute('data-thumbnail-sizing', 'uniform');
      await expect.poll(() => reference.evaluate((element: HTMLImageElement) => element.complete && element.naturalWidth === 900 && element.naturalHeight === 1600)).toBe(true);
      await expect(reference).toHaveCSS('object-fit', 'contain');
      await expect(reference).toHaveCSS('width', '54px');
      await expect(reference).toHaveCSS('height', '54px');
      const frame = tray.locator('[data-slot-index="1"]');
      await expect(frame).toHaveCSS('width', '54px');
      await expect(frame).toHaveCSS('height', '54px');
      const thumbnail = (await reference.boundingBox())!;
      const frameBox = (await frame.boundingBox())!;
      const zoom = await page.locator('.react-flow__viewport').evaluate(element => new DOMMatrixReadOnly(getComputedStyle(element).transform).a);
      expect(thumbnail.width / zoom).toBeCloseTo(54, 1);
      expect(thumbnail.height / zoom).toBeCloseTo(54, 1);
      expect(frameBox.width / zoom).toBeCloseTo(54, 1);
      expect(frameBox.height / zoom).toBeCloseTo(54, 1);
    };
    await expectUniformReference();
    await layout();
    await page.screenshot({ path: testInfo.outputPath(`image-imported-reference-${theme}.png`) });
    expect((await e2eState(page)).modelSubmissions).toHaveLength(0);
    expect((await e2eState(page)).reverseAnalysisRequests).toHaveLength(0);
    await page.evaluate(() => window.__NOVUS_E2E__!.reopenProject());
    await expect.poll(async () => (await e2eState(page)).edgeCount).toBe(1);
    const reopened = page.locator('[data-module-type="image_generation"]');
    const expand = reopened.getByRole('button', { name: 'Open image generation editor' });
    if (await expand.isVisible()) await expand.click();
    await expect(reopened.getByRole('textbox', { name: 'Image generation prompt' })).toHaveText('Keep the complete product shape');
    await expect(reopened.getByLabel('Image generation reference slots', { exact: true }).locator('img')).toHaveCount(1);
    await expectUniformReference();
  });
}
